export const config = {
  // MQ
  MESSAGE_BROKER_URL: process.env.MESSAGE_BROKER_URL,
  EXCHANGE_NAME: process.env.EXCHANGE_NAME || 'ONLINE_SHOPPING_EXCHANGE',
  QUEUE_NAME: process.env.QUEUE_NAME || 'ONLINE_SHOPPING_QUEUE',
  SHOPPING_BINDING_KEY: process.env.SHOPPING_BINDING_KEY || 'SHOPPING_SERVICE',
  CUSTOMER_BINDING_KEY: process.env.CUSTOMER_BINDING_KEY || 'CUSTOMER_SERVICE',
};

export const { MESSAGE_BROKER_URL, EXCHANGE_NAME, QUEUE_NAME, SHOPPING_BINDING_KEY, CUSTOMER_BINDING_KEY } = config;
