services:
  mongo:
    image: mongo:8.0.4
    container_name: shop_mongo
    ports:
      - 27018:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./dbdata/db:/data/db
    mem_limit: 512m
    cpu_count: 2

  rabbitmq:
    image: rabbitmq:4-management
    container_name: shop_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    mem_limit: 512m
    cpu_count: 1